package com.softjourn.sj_coin.utils;

public interface Extras {
    String EXTRAS_PRODUCTS_FEATURED_LIST = "PRODUCTS_FEATURED_LIST";
    String EXTRAS_PRODUCTS_BEST_SELLER_LIST = "EXTRAS_PRODUCTS_BEST_SELLER_LIST";
    String EXTRAS_PRODUCTS_LAST_PURCHASES_LIST = "PRODUCTS_LAST_PURCHASES_LIST";
    String EXTRAS_PRODUCTS_SEE_ALL_FRAGMENT = "TAG_PRODUCTS_SEE_ALL_FRAGMENT";
    String EXTRAS_PRODUCTS_SNACKS_LIST = "EXTRAS_PRODUCTS_SNACKS_LIST";
    String EXTRAS_PRODUCTS_DRINKS_LIST = "EXTRAS_PRODUCTS_DRINKS_LIST";

    String EXTRAS_CATEGORY = "CATEGORY";

    String EXTRAS_CONCRETE_PRODUCT = "EXTRAS_CONCRETE_PRODUCT";
}
