package com.softjourn.sj_coin.utils;

public interface Extras {
    String EXTRAS_PRODUCTS_FEATURED_LIST = "PRODUCTS_FEATURED_LIST";
    String EXTRAS_PRODUCTS_BEST_SELLER_LIST = "EXTRAS_PRODUCTS_BEST_SELLER_LIST";
    String EXTRAS_PRODUCTS_LAST_PURCHASES_LIST = "PRODUCTS_LAST_PURCHASES_LIST";
    String EXTRAS_PRODUCTS_SEE_ALL_LAST_PURCHASES_FRAGMENT = "TAG_PRODUCTS_SEE_ALL_LAST_PURCHASES_FRAGMENT";

    String EXTRAS_CATEGORY = "CATEGORY";
}
