package com.softjourn.sj_coin.utils;

public interface Extras {
    String EXTRAS_PRODUCTS_NEW_PRODUCTS_LIST = "PRODUCTS_NEW_PRODUCTS_LIST";
    String EXTRAS_PRODUCTS_BEST_SELLER_LIST = "EXTRAS_PRODUCTS_BEST_SELLER_LIST";
    String EXTRAS_FAVORITES_LIST = "EXTRAS_FAVORITES_LIST";
    String EXTRAS_PRODUCTS_SNACKS_LIST = "EXTRAS_PRODUCTS_SNACKS_LIST";
    String EXTRAS_PRODUCTS_DRINKS_LIST = "EXTRAS_PRODUCTS_DRINKS_LIST";
    String EXTRAS_PRODUCTS_ALL_LIST = "EXTRAS_PRODUCTS_ALL_LIST";

    String EXTRAS_CATEGORY = "CATEGORY";

}
